/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Nico
 */
public class interfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form interfazPrincipal
     */
    public interfazPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Interfaz de seleccion - ADMIN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonQuimica2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonAdoA = new javax.swing.JButton();
        labelInfoA = new javax.swing.JLabel();
        buttonInfoA = new javax.swing.JButton();
        labelInfoB = new javax.swing.JLabel();
        buttonInfoB = new javax.swing.JButton();
        labelAdoA = new javax.swing.JLabel();
        buttonAdoB = new javax.swing.JButton();
        labelAdoB = new javax.swing.JLabel();
        buttonMulti = new javax.swing.JButton();
        labelQuimica = new javax.swing.JLabel();
        buttonQuimica1 = new javax.swing.JButton();
        buttonElectro = new javax.swing.JButton();
        labelElectronica = new javax.swing.JLabel();
        labelMulti = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        buttonQuimica2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quimica.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 430));
        setPreferredSize(new java.awt.Dimension(430, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione el curso del cual desea ver la informacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 27, -1, -1));

        buttonAdoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrategia.png"))); // NOI18N
        buttonAdoA.setPreferredSize(new java.awt.Dimension(100, 70));
        getContentPane().add(buttonAdoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 86, 64, 64));

        labelInfoA.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelInfoA.setText("Informatica A");
        getContentPane().add(labelInfoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 156, -1, -1));

        buttonInfoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informatica.png"))); // NOI18N
        buttonInfoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInfoAActionPerformed(evt);
            }
        });
        getContentPane().add(buttonInfoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 86, 64, 64));

        labelInfoB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelInfoB.setText("Informatica B");
        getContentPane().add(labelInfoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 156, -1, -1));

        buttonInfoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informatica.png"))); // NOI18N
        getContentPane().add(buttonInfoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 86, 64, 64));

        labelAdoA.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelAdoA.setText("Ado A");
        getContentPane().add(labelAdoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 156, -1, -1));

        buttonAdoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrategia.png"))); // NOI18N
        getContentPane().add(buttonAdoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 86, 64, 64));

        labelAdoB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelAdoB.setText("Ado B");
        getContentPane().add(labelAdoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 156, -1, -1));

        buttonMulti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/claqueta.png"))); // NOI18N
        getContentPane().add(buttonMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 196, 64, 64));

        labelQuimica.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelQuimica.setText("Quimica");
        labelQuimica.setToolTipText("");
        labelQuimica.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(labelQuimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 271, -1, -1));

        buttonQuimica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quimica.png"))); // NOI18N
        getContentPane().add(buttonQuimica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 196, 64, 64));

        buttonElectro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circuito.png"))); // NOI18N
        getContentPane().add(buttonElectro, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 196, 64, 64));

        labelElectronica.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelElectronica.setText("Electronica");
        getContentPane().add(labelElectronica, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 271, -1, -1));

        labelMulti.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelMulti.setText("Multimedios");
        getContentPane().add(labelMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 271, -1, -1));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_sinFondo2.png"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInfoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInfoAActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonInfoAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdoA;
    private javax.swing.JButton buttonAdoB;
    private javax.swing.JButton buttonElectro;
    private javax.swing.JButton buttonInfoA;
    private javax.swing.JButton buttonInfoB;
    private javax.swing.JButton buttonMulti;
    private javax.swing.JButton buttonQuimica1;
    private javax.swing.JButton buttonQuimica2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel labelAdoA;
    private javax.swing.JLabel labelAdoB;
    private javax.swing.JLabel labelElectronica;
    private javax.swing.JLabel labelInfoA;
    private javax.swing.JLabel labelInfoB;
    private javax.swing.JLabel labelMulti;
    private javax.swing.JLabel labelQuimica;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
