/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.awt.Toolkit;


/**
 *
 * @author Nico
 */
public class PrincipalInterface extends javax.swing.JFrame {


    public PrincipalInterface() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Interfaz de seleccion - ADMIN");
        setSize(500,200);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/administracion.png")));
    }
    
       @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono_sinFondo2.png"));
        return retValue;
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonQuimica2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonAdoA = new javax.swing.JButton();
        labelInfoA = new javax.swing.JLabel();
        buttonReportes = new javax.swing.JButton();
        labelInfoB = new javax.swing.JLabel();
        buttonInfoB = new javax.swing.JButton();
        labelAdoA = new javax.swing.JLabel();
        buttonAdoB = new javax.swing.JButton();
        labelAdoB = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        buttonQuimica2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quimica.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 430));
        setPreferredSize(new java.awt.Dimension(430, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione el curso del cual desea ver la informacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 27, -1, -1));

        buttonAdoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrategia.png"))); // NOI18N
        buttonAdoA.setPreferredSize(new java.awt.Dimension(100, 70));
        getContentPane().add(buttonAdoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 64, 64));

        labelInfoA.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelInfoA.setText("Problemas");
        getContentPane().add(labelInfoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        buttonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informatica.png"))); // NOI18N
        buttonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReportesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 64, 64));

        labelInfoB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelInfoB.setText("Usuarios");
        getContentPane().add(labelInfoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        buttonInfoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informatica.png"))); // NOI18N
        buttonInfoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInfoBActionPerformed(evt);
            }
        });
        getContentPane().add(buttonInfoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 64, 64));

        labelAdoA.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelAdoA.setText("Laboratorios");
        getContentPane().add(labelAdoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        buttonAdoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrategia.png"))); // NOI18N
        getContentPane().add(buttonAdoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 64, 64));

        labelAdoB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelAdoB.setText("Cursos");
        getContentPane().add(labelAdoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_sinFondo2.png"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReportesActionPerformed
        // TODO add your handling code here:
        Reportes ventanaInfoA = new Reportes();
        ventanaInfoA.setVisible(true);
        
    }//GEN-LAST:event_buttonReportesActionPerformed

    private void buttonInfoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInfoBActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_buttonInfoBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalInterface().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdoA;
    private javax.swing.JButton buttonAdoB;
    private javax.swing.JButton buttonInfoB;
    private javax.swing.JButton buttonQuimica2;
    private javax.swing.JButton buttonReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel labelAdoA;
    private javax.swing.JLabel labelAdoB;
    private javax.swing.JLabel labelInfoA;
    private javax.swing.JLabel labelInfoB;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
